export const SEARCH_CITY_IN_PROGRESS = "SEARCH_CITY_IN_PROGRESS"
export const SEARCH_CITY_SUCCESS = "SEARCH_CITY_SUCCESS"
export const SEARCH_CITY_ERROR = "SEARCH_CITY_ERROR"
export const SET_SELECTED_CITY = "SET_SELECTED_CITY"

export const SEARCHED_WEATHER_REQUEST_IN_PROGRESS = 'SEARCHED_WEATHER_REQUEST_IN_PROGRESS';
export const SEARCHED_WEATHER_REQUEST_SUCCESS = ' SEARCHED_WEATHER_REQUEST_SUCCESS';
export const SEARCHED_WEATHER_REQUEST_ERROR = 'SEARCHED_WEATHER_REQUEST_ERROR';

export const ADD_FAVORITE_ITEM = 'ADD_FAVORITE_ITEM'
export const REMOVE_FAVORITE_ITEM = 'REMOVE_FAVORITE_ITEM'

export const GET_FAVOURITES_LOCATION_IN_PROGRESS = 'GetFavorite_City_IN_PROGRESS ';
export const GET_FAVOURITES_LOCATION_SUCCESS = 'GetFavorite_City_IN_SUCCESS';
export const GET_FAVOURITES_LOCATION_IN_ERROR = 'GetFavorite_City_IN_ERROR';

export const FAVOURITES_LOCATION_ADDED_TO_FAVORITE_IN_PROGRESS = 'AddFavorite_City_IN_PROGRESS';
export const FAVOURITES_LOCATION_ADDED_TO_FAVORITE_SUCCESS = 'AddFavorite_City_IN_SUCCESS';
export const FAVOURITES_LOCATION_ADDED_TO_FAVORITE_ERROR = 'AddFavorite_City_IN_ERROR';