export const SEARCHED_WEATHER_REQUEST_IN_PROGRESS = 'SearchedWeather_REQUEST_IN_PROGRESS';
export const SEARCHED_WEATHER_REQUEST_IN_SUCCESS = ' SearchedWeather_REQUEST_IN_SUCCESS';
export const SEARCHED_WEATHER_REQUEST__IN_ERROR = 'SearchedWeather_REQUEST_IN_ERROR';
export const SEARCHED_WEATHER_REQUEST_City_IN_SUCCESS = 'SearchedWeatherCity_REQUEST_IN_SUCCESS';

// export const CurrentForecast_REQUEST_IN_PROGRESS = 'CurrentForecast_REQUEST_IN_PROGRESS';
// export const CurrentForecast_REQUEST_IN_SUCCESS = 'CurrentForecast_REQUEST_IN_SUCCESS';
// export const CurrentForecast_REQUEST_IN_ERROR = 'CurrentForecast_REQUEST_IN_ERROR';

// export const FiveDaysForecast_REQUEST_IN_PROGRESS = 'FiveDaysForecast_REQUEST_IN_PROGRESS';
// export const FiveDaysForecast_REQUEST_IN_SUCCESS = 'FiveDaysForecast_REQUEST_IN_SUCCESS';
// export const FiveDaysForecast_REQUEST_IN_ERROR = 'CurrentForecast_REQUEST_IN_ERROR';


export const GET_FAVOURITES_LOCATION_IN_PROGRESS = 'GetFavorite_City_IN_PROGRESS ';
export const GET_FAVOURITES_LOCATION_IN_SUCCESS= 'GetFavorite_City_IN_SUCCESS';
export const GET_FAVOURITES_LOCATION_IN_ERROR = 'GetFavorite_City_IN_ERROR';

export const FAVOURITES_LOCATION_ADDED_TO_FAVORITE_IN_PROGRESS = 'AddFavorite_City_IN_PROGRESS';
export const FAVOURITES_LOCATION_ADDED_TO_FAVORITE_IN_SUCCESS = 'AddFavorite_City_IN_SUCCESS';
export const FAVOURITES_LOCATION_ADDED_TO_FAVORITE_IN_ERROR = 'AddFavorite_City_IN_ERROR';


export const FAVOURITES_LOCATION_DELETED_FROM_FAVORITE_IN_PROGRESS = 'AddFavorite_City_IN_PROGRESS';
export const FAVOURITES_LOCATION_DELETED_FROM_FAVORITE_IN_SUCCESS = 'AddFavorite_City_IN_SUCCESS';
export const FAVOURITES_LOCATION_DELETED_FROM_FAVORITE_IN_ERROR = 'AddFavorite_City_IN_ERROR';